### ISSUE TITLE
Button on home page not working

### ISSUE THREAD

**Issue by Saifu0** [Saifu0/promoteanybrand#9]
The button `I'm a Brand` and `I'm a Influencer` is not working. I guess we have not linked it with react-router. Should be a small change.

**Comment by Kapil-Kawathekar** [comment]
Hi @Saifu0 can you assign this to me ??

**Comment by Kapil-Kawathekar** [comment]
@Saifu0 Okay !!

**Comment by nihal-ahmad** [comment]
fixed the issue, kindly close it.
